language: scala
scala:
  - 2.10.2
before_install:
  - ./scripts/install-hadoop-for-tests.sh
  - ./scripts/install-hbase-for-tests.sh
before_script:
  - ./scripts/start-hadoop.sh
  - ./scripts/start-hbase.sh
after_script:
  - ./scripts/stop-hbase.sh
  - ./scripts/stop-hadoop.sh
